adding retry mechinism for pushing to github

diff --git a/tasks/push-to-github.yaml b/tasks/push-to-github.yaml
--- a/tasks/push-to-github.yaml
+++ b/tasks/push-to-github.yaml
@@ -92,11 +92,10 @@ spec:
 
         cd repo
         git fetch origin
-
         if git ls-remote --heads origin | grep -q "refs/heads/$(params.revision)"; then
             echo "Branch $(params.revision) exists on remote. Checking out..."
             git checkout -B "$(params.revision)" origin/"$(params.revision)"
-            git reset --hard origin/"$(params.revision)"
+            git pull --rebase origin "$(params.revision)"
         else
             echo "Branch $(params.revision) does not exist. Creating and pushing it..."
             git checkout -b "$(params.revision)"
@@ -122,7 +121,25 @@ spec:
         ' "$FILE_NAME" > tmp.json && mv tmp.json "$FILE_NAME"
 
         git add "$FILE_NAME"
-
         APP_NAME=$(echo "${SNAPSHOT_SPEC}" | jq -r '.snapshot_spec.application')
         git commit -m ":robot:[RHTAS-build-bot] Promote "${APP_NAME}" to candidate"
-        git push origin "$(params.revision)" --force
+
+        MAX_RETRIES=5
+        attempt=0
+        while [ $attempt -lt $MAX_RETRIES ]; do
+            git fetch origin
+            git rebase origin/"$(params.revision)" || { echo "Rebase failed, retrying..."; git rebase --abort; }
+            if git push origin "$(params.revision)"; then
+                echo "Push successful"
+                break
+            else
+                attempt=$(( attempt + 1 ))
+                sleep_time=$(( 2 ** attempt ))
+                sleep $sleep_time
+            fi
+        done
+
+        if [ $attempt -eq $MAX_RETRIES ]; then
+            echo "Push failed after $MAX_RETRIES attempts. Exiting."
+            exit 1
+        fi
